#!/usr/bin/env python3

import subprocess


def toggle_native_fullscreen_on_focused_window():
    subprocess.run(
        [
            "swift",
            "-e",
            """
import Cocoa

guard let app = NSWorkspace.shared.frontmostApplication else { exit(1) }
let appRef = AXUIElementCreateApplication(app.processIdentifier)

app.activate(options: [])

var windowsRef: CFTypeRef?
AXUIElementCopyAttributeValue(appRef, kAXWindowsAttribute as CFString, &windowsRef)
guard let windows = windowsRef as? [AXUIElement], !windows.isEmpty else { exit(1) }
let win = windows[0]

var fsRef: CFTypeRef?
AXUIElementCopyAttributeValue(win, "AXFullScreen" as CFString, &fsRef)
let isFullscreen = (fsRef as? Bool) ?? false
let newState = (!isFullscreen) as CFBoolean
AXUIElementSetAttributeValue(win, "AXFullScreen" as CFString, newState)
""",
        ]
    )


def main():
    toggle_native_fullscreen_on_focused_window()


if __name__ == "__main__":
    main()
