#!/bin/sh

set -eu

primaryUserId="$1"
primaryUserHomeDirectory="$2"

orphanSystemLaunchDaemonPlists="
/Library/LaunchDaemons/org.nixos.start_karabiner_daemons.plist
/Library/LaunchDaemons/org.nixos.setsuid_karabiner_session_monitor.plist
"

orphanSystemLaunchDaemonLabels="
org.nixos.start_karabiner_daemons
org.nixos.setsuid_karabiner_session_monitor
"

orphanUserLaunchAgentPlist="$primaryUserHomeDirectory/Library/LaunchAgents/org.nixos.activate_karabiner_system_ext.plist"
orphanUserLaunchAgentLabel="org.nixos.activate_karabiner_system_ext"

orphanVirtualHidDeviceManagerDirectory="/Applications/.Nix-Karabiner"

for orphanSystemLaunchDaemonLabel in $orphanSystemLaunchDaemonLabels; do
	/bin/launchctl bootout "system/$orphanSystemLaunchDaemonLabel" 2>/dev/null || true
done

for orphanSystemLaunchDaemonPlist in $orphanSystemLaunchDaemonPlists; do
	rm -f "$orphanSystemLaunchDaemonPlist"
done

/bin/launchctl bootout "gui/$primaryUserId/$orphanUserLaunchAgentLabel" 2>/dev/null || true
rm -f "$orphanUserLaunchAgentPlist"

if [ -d "$orphanVirtualHidDeviceManagerDirectory" ]; then
	chflags -R nouchg "$orphanVirtualHidDeviceManagerDirectory" 2>/dev/null || true
	rm -rf "$orphanVirtualHidDeviceManagerDirectory"
fi
