#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  echo "Usage: $0 <port>"
  exit 1
fi

PORT=$1

PIDs=$(lsof -ti:"$PORT")

if [ -z "$PIDs" ]; then
  echo "No process found listening on port $PORT."
  exit 1
else
  for PID in $PIDs; do
    if kill -9 "$PID" 2>/dev/null; then
      echo "Process $PID on port $PORT has been killed."
    else
      echo "Failed to kill process $PID on port $PORT."
    fi
  done
fi
