#!/usr/bin/env bash
set -euo pipefail

focused_application_pid=$(aerospace list-windows --focused --format '%{app-pid}')
[ -z "$focused_application_pid" ] && exit 0
aerospace close
kill "$focused_application_pid" 2>/dev/null
(sleep 1 && kill -0 "$focused_application_pid" 2>/dev/null && kill -9 "$focused_application_pid" 2>/dev/null) &
