{ pkgs }:
{
  NPM_CONFIG_PREFIX = "/nonexistent";
  DISABLE_AUTOUPDATER = "1";
  DISABLE_INSTALLATION_CHECKS = "1";

  CLAUDE_CODE_SHELL = "${pkgs.bash}/bin/bash";
  CLAUDE_BASH_NO_LOGIN = "1";
  CLAUDE_DANGEROUSLY_DISABLE_SANDBOX = "true";
  CLAUDE_SKIP_PERMISSIONS = "true";
  CLAUDE_AUTOCOMPACT_PCT_OVERRIDE = "80";
  CLAUDE_CODE_DISABLE_TERMINAL_TITLE = "true";
  CLAUDE_CODE_NO_FLICKER = "1";
  CLAUDE_CODE_SCROLL_SPEED = "3";
  CLAUDE_ENABLE_STREAM_WATCHDOG = "1";
  CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS = "1";

  BASH_DEFAULT_TIMEOUT_MS = "120000";
  BASH_MAX_TIMEOUT_MS = "600000";
  BASH_ENV = "$HOME/.dotfiles/home/modules/terminal/shell/aliases.sh";
}
